// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hynpysnltzhhihvhkoxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bnB5c25sdHpoaGlodmhrb3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjc1ODgsImV4cCI6MjA3Mjg0MzU4OH0.7JHxJVqWEXP9Cu1Vn5koXu8SNLNpgm4xse-ivMjud2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});